import React from 'react';

const TimeLine = props => {
  return (
    <div className="timeline">
      <ul>
        <li>
          <span>00:00</span>
        </li>
        <li>
          <span>00:30</span>
        </li>
        <li>
          <span>01:00</span>
        </li>
        <li>
          <span>01:30</span>
        </li>
        <li>
          <span>02:00</span>
        </li>
        <li>
          <span>02:30</span>
        </li>
        <li>
          <span>03:00</span>
        </li>
        <li>
          <span>03:30</span>
        </li>
        <li>
          <span>04:00</span>
        </li>
        <li>
          <span>04:30</span>
        </li>
        <li>
          <span>05:00</span>
        </li>
        <li>
          <span>05:30</span>
        </li>
        <li>
          <span>06:00</span>
        </li>
        <li>
          <span>06:30</span>
        </li>
        <li>
          <span>07:00</span>
        </li>
        <li>
          <span>07:30</span>
        </li>
        <li>
          <span>08:00</span>
        </li>
        <li>
          <span>08:30</span>
        </li>

        <li>
          <span>09:00</span>
        </li>
        <li>
          <span>09:30</span>
        </li>
        <li>
          <span>10:00</span>
        </li>
        <li>
          <span>10:30</span>
        </li>
        <li>
          <span>11:00</span>
        </li>
        <li>
          <span>11:30</span>
        </li>
        <li>
          <span>12:00</span>
        </li>
        <li>
          <span>12:30</span>
        </li>
        <li>
          <span>13:00</span>
        </li>
        <li>
          <span>13:30</span>
        </li>
        <li>
          <span>14:00</span>
        </li>
        <li>
          <span>14:30</span>
        </li>
        <li>
          <span>15:00</span>
        </li>
        <li>
          <span>15:30</span>
        </li>
        <li>
          <span>16:00</span>
        </li>
        <li>
          <span>16:30</span>
        </li>
        <li>
          <span>17:00</span>
        </li>
        <li>
          <span>17:30</span>
        </li>
        <li>
          <span>18:00</span>
        </li>

        <li>
          <span>18:30</span>
        </li>
        <li>
          <span>19:00</span>
        </li>
        <li>
          <span>19:30</span>
        </li>
        <li>
          <span>20:00</span>
        </li>
        <li>
          <span>20:30</span>
        </li>
        <li>
          <span>21:00</span>
        </li>
        <li>
          <span>21:30</span>
        </li>
        <li>
          <span>22:00</span>
        </li>
        <li>
          <span>22:30</span>
        </li>
        <li>
          <span>23:00</span>
        </li>
        <li>
          <span>23:30</span>
        </li>
      </ul>
    </div>
  );
};

export default TimeLine;
