import React from 'react';

const TimeLine = props => {
  return (
    <div className="timeline">
      <ul>
        <li>
          <span>
            <b>00:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>00:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>01:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>01:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>02:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>02:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>03:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>03:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>04:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>04:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>05:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>05:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>06:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>06:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>07:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>07:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>08:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>08:30</b>
          </span>
        </li>

        <li>
          <span>
            <b>09:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>09:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>10:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>10:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>11:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>11:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>12:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>12:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>13:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>13:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>14:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>14:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>15:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>15:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>16:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>16:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>17:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>17:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>18:00</b>
          </span>
        </li>

        <li>
          <span>
            <b>18:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>19:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>19:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>20:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>20:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>21:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>21:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>22:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>22:30</b>
          </span>
        </li>
        <li>
          <span>
            <b>23:00</b>
          </span>
        </li>
        <li>
          <span>
            <b>23:30</b>
          </span>
        </li>
      </ul>
    </div>
  );
};

export default TimeLine;
